#!/usr/bin/env bash
#this script configures Nginx server so that 
#/redirect_me is redirecting to another page
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get install -y nginx
sudo sh -c 'echo "Ceci n '\'' est pas une page" > /var/www/html/index.nginx-debian.html'
REDIRECT="\\\tlocation \/redirect_me{\n\t\treturn 301 http:\/\/www.youtube.com/watch?v=QH2-TGUlwu4;}"
sudo sed -i "47i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx restart