#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Define a variable to hold the hostname
hostname=$(hostname)

# Configure Nginx to include a custom HTTP header with the hostname
sudo sed -i "/http {/a \        set \$server_name ${hostname};\n" /etc/nginx/nginx.conf
sudo sed -i "/server {/a \        add_header X-Served-By \$server_name;\n" /etc/nginx/sites-available/default

# Restart Nginx
sudo systemctl restart nginx