#!/usr/bin/env bash

# Update the package index and install HAproxy
sudo apt update
sudo apt install haproxy -y
chmod u+w haproxy.cfg
# Configure HAproxy to send traffic to web-01 and web-02 using roundrobin algorithm
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_front
   bind *:80
   mode http
   default_backend http_back

backend http_back
   balance roundrobin
   server [STUDENT_ID]-web-01 [STUDENT_ID]-web-01:80 check
   server [STUDENT_ID]-web-02 [STUDENT_ID]-web-02:80 check
EOT

# Verify the HAproxy configuration
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Configure HAproxy to be managed via an init script
sudo tee /etc/default/haproxy > /dev/null <<EOT
ENABLED=1
EOT

# Start and enable the HAproxy service
sudo systemctl start haproxy
sudo systemctl enable haproxy

# Update the hostname to match the requirements
sudo hostnamectl set-hostname [STUDENT_ID]-lb-01

# Reboot the machine to apply the changes
sudo reboot