#!/usr/bin/env bash

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx as a load balancer
sudo rm /etc/nginx/sites-enabled/default
sudo chmod -R 777 /etc/nginx/sites-available
sudo touch /etc/nginx/sites-available/load-balancer
sudo ln -s /etc/nginx/sites-available/load-balancer /etc/nginx/sites-enabled/load-balancer
sudo echo "upstream backend {
    server 54.208.180.150;
        server 100.25.137.136;
    }

server {
    listen 80;
        location / {
	        proxy_pass http://backend;
		    }
    }" > /etc/nginx/sites-available/load-balancer

# Restart Nginx
sudo systemctl restart nginx
